name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  lottie: ^3.2.0
  cupertino_icons: ^1.0.8
  skeletonizer: ^1.4.3
  intl: ^0.20.2
  email_validator: ^3.0.0
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.4
  permission_handler: ^12.0.0+1
  logger: ^2.5.0
  get: ^4.7.2
  # image_picker: ^1.0.6
  dotted_border: ^2.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/demo-icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - .env

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir/avenir_reguler.ttf
          weight: 400
        - asset: assets/fonts/avenir/avenir_bold.ttf
          weight: 700
        - asset: assets/fonts/avenir/avenir_light.ttf
          weight: 300
        - asset: assets/fonts/avenir/avenir_extra_bold.ttf
          weight: 800